# Generated by Django 3.0.1 on 2020-01-13 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgapp', '0002_auto_20200112_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opposite_bag', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bgapp.WordBag')),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='wordbag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='words', to='bgapp.WordBag'),
        ),
    ]
