# Generated by Django 3.0.1 on 2020-01-14 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgapp', '0003_auto_20200113_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordbag',
            name='opposite_bag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bgapp.WordBag'),
        ),
    ]
