# Generated by Django 3.0 on 2020-01-23 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgapp', '0004_auto_20200114_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concamp',
            name='user_count',
        ),
        migrations.RemoveField(
            model_name='procamp',
            name='user_count',
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bgapp.Conversation'),
        ),
    ]
