# Generated by Django 3.0 on 2020-01-24 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgapp', '0005_auto_20200123_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ban',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sessioninfo',
            options={},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='timeStart',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
