# Generated by Django 3.0.2 on 2020-01-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgapp', '0006_auto_20200124_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessioninfo',
            options={'ordering': ['-timeEnd']},
        ),
        migrations.AddField(
            model_name='user',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
