# Generated by Django 3.0.2 on 2020-01-26 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgapp', '0007_auto_20200126_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='bgapp.User'),
        ),
        migrations.AlterField(
            model_name='concamp',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='con_camp', to='bgapp.Topic'),
        ),
        migrations.AlterField(
            model_name='procamp',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_camp', to='bgapp.Topic'),
        ),
        migrations.AlterField(
            model_name='sessioninfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to='bgapp.User'),
        ),
        migrations.AlterField(
            model_name='useropinion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='bgapp.User'),
        ),
    ]
