# Generated by Django 3.0.2 on 2020-01-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgapp', '0009_auto_20200127_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelid',
            name='channelID',
            field=models.TextField(max_length=100),
        ),
    ]
