# Generated by Django 3.0.2 on 2020-01-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgapp', '0010_auto_20200127_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='channelID',
            field=models.TextField(default=None, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ChannelID',
        ),
    ]
